# Site settings
title: Angelatte's Dev Blog
email: angelaevans@ufl.edu
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Angela Evans, Computer Science Senior at the University of Florida. Feel free to contact with any comments/suggestions!
baseurl: "/dev" # the subpath of your site, e.g. /blog/
url: "http://angelaevans.me" # the base hostname & protocol for your site
twitter_username: ange_latte
github_username:  angelaevans

# Build settings
highlighter: rouge
markdown: kramdown
